dim - allow NULL MX records (RFC7505)
1and1/dim pull request #213
Opened 2022-02-15 16:32 UTC by Srudush

To allow NULL MX records it was necessary to extend the validate_args
method with the context of other fields.

According to RFC7505 a preference of 0 is allowed when the target is
only '.' and the same in the other direction.
That means that both fields need to be checked in such cases which
requires the context of the other field.

In the future this allows us to implement similar validations for other
record types.

Fixes #128

2022-03-02 13:47 UTC, Srudush commented on dim/dim/models/dns.py
> +                kwargs[field] = validate(None, field, kwargs[field], **({i:kwargs[i] for i in kwargs if i != field}))
Thanks for trying that :)

2022-03-04 09:59 UTC, Srudush commented
I have pushed a couple changes to fix the broken test cases. There was also a completely wrong SQLAlchemy statement.
In addition I have adjusted the error messages to make it clearer which case is blocking.

2022-03-04 09:59 UTC, Srudush commented on dim/dim/models/dns.py
> +                kwargs[field] = validate(None, field, kwargs[field], **({i:kwargs[i] for i in kwargs if i != field}))
I have added **kwargs to all other validate functions to fix this.

2022-03-07 12:19 UTC, zeromind commented on dim/dim/dns.py
> +                logging.info('WOOOOSA %s -> %s -> %s', new_rr, samerr, rrs)
Debug output

2022-03-07 12:28 UTC, zeromind requested changes
LGTM, but there's some debug output that should be removed, added a suggested change for it

pytests/tests look good

2022-03-07 12:28 UTC, zeromind commented on dim/dim/dns.py
> +                logging.info('WOOOOSA %s -> %s -> %s', new_rr, samerr, rrs)
```suggestion
```

2022-03-07 12:51 UTC, Srudush commented on dim/dim/dns.py
> +                logging.info('WOOOOSA %s -> %s -> %s', new_rr, samerr, rrs)
oh thanks :)

2022-03-07 12:54 UTC, merged