Issue -269 Fixed
1and1/dim pull request #275
Opened 2024-06-11 13:12 UTC by zakriya057

2024-06-11 13:28 UTC, miesi commented
```
$ ndcli create layer3domain test type vrf rd 256:256
type name    properties comment
vrf  default rd:8560:1  
vrf  test    rd:256:256
```
This is the output of list layer3domains

Please correct to something like
```
$ ndcli create layer3domain test type vrf rd 256:256
$ ndcli list layer3domains
type name    properties comment
vrf  default rd:8560:1  
vrf  test    rd:256:256
```

2024-06-11 13:33 UTC, miesi commented
Please remove dim-testsuite/SHOW, dim_ndcli_test.patch from PR

Please add a $ ndcli list containers layer3domain test 0.0.0.0/0 after you have created v4 and v6 container in l3d test.

2024-06-18 12:20 UTC, zeromind commented on dim-testsuite/t/container-create-1.t
> +INFO - Creating container 0.0.0.0/0 in layer3domain defaul
```suggestion
INFO - Creating container 0.0.0.0/0 in layer3domain default
```

2024-06-18 12:22 UTC, zeromind commented on dim-testsuite/t/container-create-1.t
> +ntainer 0.0.0.0/0 layer3domain default
```suggestion
```

2024-06-18 12:26 UTC, zeromind commented on dim-testsuite/t/container-create-1.t
> +$ ndcli create container 0.0.0.0/0
```suggestion
$ ndcli create layer3domain test type vrf rd 256:256

$ ndcli create container 0.0.0.0/0
```

2024-06-18 12:38 UTC, zakriya057 commented
Accept the changes in test cases.

2024-06-18 12:38 UTC, zakriya057 commented
Accept the changes

2024-06-18 12:39 UTC, zakriya057 reviewed
accept the changes

2024-06-18 12:41 UTC, zeromind commented on dim-testsuite/t/group-modify-1.t
> +user2-test
```suggestion
user2
```

2024-06-19 09:53 UTC, zeromind requested changes
Minor formatting adjustments are necessary.

2024-06-19 09:53 UTC, zeromind commented on dim-testsuite/t/container-list-4.t
> +
```suggestion
```

2024-06-19 09:53 UTC, zeromind commented on dim/dim/rpc.py
> +
```suggestion
```

2024-06-19 09:53 UTC, zeromind commented on dim/dim/rpc.py
> -
Leave empty line

2024-06-19 09:53 UTC, zeromind commented on dim/dim/rpc.py
> -
Leave empty line

2024-06-20 07:35 UTC, miesi approved these changes
Please remove dim.cfg and group-modify-1.t from this PR then merge in master ok.

2024-06-20 07:35 UTC, miesi commented on dim-testsuite/t/group-modify-1.t
@zakriya057 please remove changes to `group-modify-1.t` from this PR.

2024-06-25 08:01 UTC, zakriya057 commented
I have removed the file and reverted the change from group-modify-1.t Now see changes in 2 files and 2 new files of test cases added in this PR.

2024-06-25 11:50 UTC, merged